default_language_version:
  python: python3.12

repos:
  # general checks (see here: https://pre-commit.com/hooks.html)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
        args: [ --allow-multiple-documents ]
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: check-symlinks

  # black - formatting
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        name: black
        args:
          - "--config"
          - "./pyproject.toml"

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.284
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix, "--config", "./pyproject.toml" ]
        types_or: [ python, pyi, jupyter ]
        stages: [ pre-commit ]