# Generated by Django 5.2 on 2025-05-10 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("version", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "token_limit",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum number of tokens the model can process in a single request",  # noqa: E501
                        null=True,
                    ),
                ),
                (
                    "max_context_length",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum context length for the model",
                        null=True,
                    ),
                ),
                (
                    "max_response_length",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum response length for the model",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Model",
                "verbose_name_plural": "AI Models",
                "db_table": "ai_model",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AIModelProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("api_key", models.CharField(max_length=255)),
                (
                    "models",
                    models.ManyToManyField(related_name="providers", to="AI.aimodel"),
                ),
            ],
            options={
                "verbose_name": "AI Model Provider",
                "verbose_name_plural": "AI Model Providers",
                "db_table": "ai_model_provider",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Prompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt", models.TextField()),
                ("response", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indicates if the prompt is active or not",
                    ),
                ),
                (
                    "ai_model",
                    models.ForeignKey(
                        blank=True,
                        help_text="The AI model using this prompt",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prompts",
                        to="AI.aimodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prompt",
                "verbose_name_plural": "Prompts",
                "db_table": "prompt",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PromptCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "prompts",
                    models.ManyToManyField(related_name="categories", to="AI.prompt"),
                ),
            ],
            options={
                "verbose_name": "Prompt Category",
                "verbose_name_plural": "Prompt Categories",
                "db_table": "prompt_category",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PromptVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "prompt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="AI.prompt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prompt Version",
                "verbose_name_plural": "Prompt Versions",
                "db_table": "prompt_version",
                "ordering": ["-created_at"],
            },
        ),
    ]
