# Generated by Django 5.2 on 2025-05-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("settings", models.JSONField(default=dict)),
            ],
            options={
                "verbose_name": "Chat User",
                "verbose_name_plural": "Chat Users",
                "db_table": "chat_user",
            },
        ),
    ]
